version: '3.7'
services:
  db:
    image: postgres:latest
    volumes:
      - database_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: H6bLerShrQ
    networks:
      - data-net
    ports:
      - '5432:5432'


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - data-net
    restart: unless-stopped
    logging:
      driver: none

  auth-micro:
    networks:
      - data-net
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    build: src/auth-micro

    privileged: true

  todos-micro:
    networks:
      - data-net
    depends_on:
      - db
    links:
      - db
    ports:
      - '8090:8080'
    build: src/todos-micro

    privileged: true

volumes:
  database_postgres:
  pgadmin:



networks:
  data-net: